### ISSUE TITLE
Force close since update to 1.0.1

### ISSUE THREAD

**Issue by qfvldaa2xn** [SecUSo/privacy-friendly-ruler#4] opened 2016-12-22 12:04 UTC
Version 1.0 was working like a charm.
Just tried to update to 1.0.1 and I get a force close right after trying to start the app on Android CM11 4.4.4.

**Comment by Yonjuni** [comment] 2016-12-22 12:51
Okay thanks. It's interesting, because we have just updated strings.

**Comment by qfvldaa2xn** [comment] 2016-12-22 13:46
I updated in the F-Droid app. But downgrading to 1.0 in F-Droid helps though.

**Comment by Yonjuni** [comment] 2016-12-22 16:33
I re-produced the issue it is a `android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013` caused by the SplashActivity, a file that has not been changed, neither the resources have been.

**Comment by Yonjuni** [comment] 2016-12-22 16:39
This problem is fixed with commit b6f98c74d267007b729c6a848b7f7a460c8ab852 and will be solved in version 1.0.2

**Closed by Yonjuni** 2016-12-22 16:39 UTC
Labels: investigation required

**Comment by Yonjuni** [comment] 2016-12-22 19:09
@qfvldaa2xn In case you wish to have a look at the app before the F-Droid update, you can get the apk from here: https://github.com/SecUSo/privacy-friendly-ruler/releases/tag/v1.1
